micronaut:
    application:
        name: demo

datasources:
    default:
        dialect: POSTGRES
        driverClassName: org.postgresql.Driver
        password: secret
        schema-generate: CREATE_DROP
        url: jdbc:postgresql://localhost:5432/demo
        username: postgres

jpa:
    default:
        compile-time-hibernate-proxies: true
        entity-scan:
            packages: 'com.example.persistence.entities'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true

#mongodb:
#    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
#r2dbc:
#    datasources:
#        default:
#            password: secret
#            url: r2dbc:postgresql://localhost:5432/postgres
#            username: postgres
#vertx:
#    pg:
#        client:
#            database: demo
#            database.maxSize: 5
#            database.user: postgres
#            database.password: secret
#            host: localhost
#            port: 5432
#            user: postgres
#            password: secret
#            maxSize: 5